const meats = `FRIED CHICKEN - BBQ RIBS - HOT LINKS - BRISKET - BURGERS - BBQ CHICKEN - OX TAILS - TURKEY - NECK BONES - HAM - SPAGHETTI - FRIED RIBS - ROAST - TACO BAR`;
const seafood = `CRAB BOIL - SHRIMP - FISH - GUMBO`;
const sides = `BAKED BEANS - GREENS - MAC-N-CHEESE - CABBAGE - SHRIMP FRIED RICE - ENCHILADAS - MEATBALLS - VEGETABLE STIR FRY - POTATOES - YAMS - PINTO BEANS`;

export{
    meats,
    seafood,
    sides
}